name: lazy_load_dart_and_flutter
description: "Practice based on LearnDartFlutter YouTube channel."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: 1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: 2.4.10
  go_router: 13.2.0
  riverpod_annotation: 2.3.4
  surf_lint_rules: 3.0.0

dev_dependencies:
  build_runner: 2.4.8
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: 2.3.11
  riverpod_lint: 2.3.9

flutter:
  uses-material-design: true
  generate: true
